### ISSUE TITLE
Create vlog4j-reasoner module to move vlog-specific code from core

### ISSUE THREAD

**Issue by mkroetzsch** [knowsys/rulewerk#127]
It would be good to move the reasoner implementation package out of core to an own module. The core module should not depend on vlog4j-base. The reasoner interfaces would remain in core.

**Comment by irina-dragoste** [comment]
I started implementing this change on branch [reasoner-module-#127]( https://github.com/knowsys/vlog4j/tree/reasoner-module-%23127.), where I moved vLog specific code to new  `vlog4j-vlog` module.

As seen in the code, this separation raises several issues:
- Every `DataSource `implementation contains code that is vLog specific. Moreover, some of them implement `VLogDataSource `interface. If these classes are moved to `vlog4j-vlog` module, then the `vlog4j-parser` module would need a `vlog4j-vlog` dependency.

- Some package-private classes and methods need now to become public (for example, `QueryResultImpl`,  if we want to keep them in `vlog4j-core`).
- As `InMemoryDataSource` uses a package-private method of `TermToVLogConverter`, it requires it to be in the same package as the to/from vLog converters and the `VLogjReasoner`
-` vlog4j-rdf `has a test dependency to `vlog4j-vlog`, because it tests reasoning over some RDF data. Perhaps these tests should be removed.
- `EmptyQueryResultIterator `is now the only class in `vlog4j.core.reasoner.implementation` package. Perhaps it should be moved to `vlog4j-vlog` .

**Comment by mmarx** [comment]
I've picked this up again as part of the modular-reasoners branch in 10c1fd75629a0ac6b834b7552cd58d28f89359a6. 

* Backend-specific DataSource code is now handled by a `DataSourceConfigurationVisitor` implemented by each reasoner backend, so DataSources stay in `rulewerk-core`, and `rulewerk-parser` avoids a dependency on `rulewerk-vlog`. 
* The test dependency of `rulewerk-rdf` on `rulewerk-vlog` remains for now; moving the tests to `rulewerk-vlog` would then have that depending on `rulewerk-rdf`. It seems to me that such tests are prime candidates for splitting out into an integration-tests module. 
* I have broken the `InMemoryDataSource` dependency on `TermToVLogConverter` by reimplementing the code (admittedly, this is not the nicest solution, but better than nothing). In general, the `InMemoryDataSource` interface is quite VLog-specific right now and could benefit from being made more generic.
* `vlog4j.core.reasoner.implementation` still contains more than a single class, even though some of them are now public instead of package-private.

**Comment by irina-dragoste** [comment]
InMemoryDataSource  is now abstract, and we have VLogInMemoryDataSource for VLog-specific implementation
