### ISSUE TITLE
JavaDoc search feature fails

### ISSUE THREAD

**Issue by mkroetzsch** [knowsys/rulewerk#170]
When using the "search" field in the JavaDoc site to find a type produces URLs that are not found (404 error). This is due to an additional "/undefined" that is put into the URL. The content can be found by removing this part.

Apparently, this is a known problem: https://stackoverflow.com/questions/52326318/maven-javadoc-search-redirects-to-undefined-url
However, the solutions given there are not completely nice either (main solution breaks links to standard classes). Maybe we could somehow make JavaDoc use our actual module structure properly?

**Comment by mmarx** [comment]
Since we're still using javadoc in the Java 8 compatibility mode, that workaround works perfectly without breaking links to standard classes (since they're not yet part of a module). However, this breaks building the Javadoc on a Java 8 JDK, as that version doesn't know about the `--no-module-directories` option. It should be possible to fix that by using a separate profile for that.
